### ISSUE TITLE
Addition Example for December 1

### ISSUE THREAD

**Issue by arnabsinha99** [SVCE-ACM/A-December-of-Algorithms-2020#9]
Could you give an example when the square of a number has an odd number of digits. In that case, what would constitute the left and the right half?

**Comment by shriram2301** [comment]
could we just append a 0 on the left half for this case? Please do resolve this ambiguity.

**Comment by shriram2301** [comment]
also could we get more test cases for this problem?

**Comment by Harshini-rs** [comment]
If the square of a number has an odd number of digits, then take the 'k' digits (same as that of the input) as the right half and remaining as the left half.
For example:
If the input is 297(divisible by 3)
k=3  (because 297 has 3 digits)
297^2=88209
so right half=209(k=3 digits) and left half=88
88+209=297
Also, 297 is divisible by 3
so the output is Safe
